apiVersion: v1
kind: ReplicationController
metadata:
  name: couchbase-rc
  labels:
    name: couchbase
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: couchbase
    spec:
      containers:
      - name: couchbase-rc-pod
        image: couchbase/server
        ports:
        - containerPort: 8080
