apiVersion: v1
kind: ReplicationController
metadata:
  name: my-wildfly
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
      - name: wildfly
        image: jboss/wildfly
        ports:
        - containerPort: 8080
