apiVersion: v1
kind: Pod
metadata:
  name: bootiful-couchbase
  labels:
    name: bootiful-couchbase-pod
spec:
  containers:
  - name: bootiful-couchbase
    image: arungupta/bootiful-couchbase
    env:
    - name: COUCHBASE_URI
      value: couchbase-service